import Head from 'next/head'
import React, { useState, useEffect } from 'react';
import Link from 'next/link'
import styles from '../styles/Home.module.css'
export default function Home() {
  // if ((user.name.toString().toLowerCase().indexOf(searchKey) > -1)
  const [productListFilter, setProductListFilter] = useState([]);
  useEffect(() => {
    let emplyees = [{
      id: 1,
      name: "Nguyen Hoang Duy",
      sex: 0,
      address: "Giai Xuan, Phong DIen, Can Tho",
      phoneNumber: "0375575127",
      email: "duy2205@gail.com",
      position: "Truong Phong",
    },
    {
      id: 2,
      name: "Nguyen Minh Nguyet",
      sex: 1,
      address: "Long Tri, Long My, Hau Giang",
      phoneNumber: "0971972102",
      email: "nguyenminhnguyet@gail.com",
      position: "Truong Phong",
    }
    ];
    if (!localStorage.getItem('emplyeeList') || JSON.parse(localStorage.getItem('emplyeeList')) === "" || localStorage.getItem('emplyeeList') == "") {
      localStorage.setItem("emplyeeList", JSON.stringify(emplyees))
    }

    setProductListFilter(JSON.parse(localStorage.getItem('emplyeeList')));

  }, []);

  const onDelete = (id) => {
    console.log(id);
    const new_arr = productListFilter.filter(item => item.id !== id);
    setProductListFilter(new_arr);
    localStorage.setItem("emplyeeList", JSON.stringify(new_arr))
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tw-elements/dist/css/index.min.css" />
        <script src="https://cdn.tailwindcss.com"></script>
        <script src="https://cdn.jsdelivr.net/npm/tw-elements/dist/js/index.min.js"></script>
      </Head>

      <main >
        <Link href="/edit/null">
          <button type="button" className="button-form">
            <a>Thêm</a>
          </button>
        </Link>
        <table>
          <thead>
            <tr>
              <th>
                STT
              </th>
              <th>
                Họ và tên
              </th>
              <th>
                Nữ
              </th>
              <th>
                Địa chỉ
              </th>
              <th>
                Điện thoại
              </th>
              <th>
                Email
              </th>
              <th>
                Chức vụ
              </th>
              <th>
                Sửa
              </th>
              <th>
                Xóa
              </th>
            </tr>
          </thead>
          <tbody>
            {productListFilter && productListFilter.map((emmp, index) =>
              <tr key={index}>
                <td>
                  {/* {index + 1} */}
                  {emmp.id}
                </td>
                <td>
                  {emmp.name}
                </td>
                <td>
                  {emmp.sex == 1 ? "Nu" : null}
                </td>
                <td>
                  {emmp.address}
                </td>
                <td>
                  {emmp.phoneNumber}
                </td>
                <td>
                  {emmp.email}
                </td>
                <td>
                  {emmp.position}
                </td>
                <td>
                  <Link href={`/edit/${emmp.id}`}>
                    <button type="button" className="button-form">Sửa</button>
                  </Link>
                </td>
                <td>
                  {/* <button type="button"
                    onClick={() => onDelete(emmp.id)}
                    className="button-form" >Xóa</button> */}
                  <div className="popup-link button-form">
                    <a href={`#popup2-${emmp.id}`}>Xóa</a>
                  </div>
                  <div id={`popup2-${emmp.id}`} className="popup-container popup-style-2">
                    <div className="popup-content">
                      <a href="#" className="close">&times;</a>
                      <h3>Popup 2 - {emmp.id} </h3>
                      <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
                      <a href="#" onClick={() => onDelete(emmp.id)} className="button-form">Xóa</a>
                    </div>
                  </div>
                </td>

              </tr>
            )}
          </tbody>
        </table>
        <div>


        </div>
      </main>


    </div>
  )
}


